### PR TITLE
Fixing some security advisories by updating deps (closes #112)

### LINKED ISSUE #112: Fix axios security advisory
image

### PR DESCRIPTION
**Pull request by ecamellini**
Closes [#2521027](https://buildo.kaiten.io/space/[object Object]/card/2521027)

⚠️ The line above was added during the automatic migration of all github project issues to Kaiten. The old GH issue link is kept here for reference (it is now deprecated, continue follow the original issue on Kaiten).

Closes #112 

Tests pass:
image

### CODE REVIEW

**Comment by ecamellini** [comment]
@giogonzo let's wait for smooth-release to be released after https://github.com/buildo/smooth-release/issues/117 was merged.

**Review by giogonzo — APPROVED** [review]
@ecamellini looks 👍 

Although looking at the [changelog](https://github.com/axios/axios/blob/master/CHANGELOG.md) nothing seems to be breaking, I would test the new axios version on a project (the tests here are just snapshots, nothing gets really run). Also note that it doesn't come as a prod `dependency`, so in order to fix the advisory on the final project, axios should be updated there

**Comment by ecamellini** [comment]
@giogonzo true, it must be updated as dependency in `bento` too.

**Comment by ecamellini** [comment]
Just tested it: it seems to work as expected both while running `metarpheus` and while performing actuall calls at runtime. I'll merge and release.

**Pull request merged**
